repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff-format
        args: [app/]
        files: ^backend/
      - id: ruff
        args: [check, app/]
        files: ^backend/

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd frontend && npx eslint .'
        language: system
        files: ^frontend/src/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false
